# Generated by Django 4.1 on 2022-08-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(height_field='480', upload_to='equipe', verbose_name='Imagem', width_field='480'),
        ),
    ]
