# Generated by Django 4.1 on 2022-08-31 21:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
