# Generated by Django 4.1 on 2022-09-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cargo_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('recurso', models.CharField(max_length=30, verbose_name='Nome do recurso:')),
                ('descricao', models.TextField(max_length=250, verbose_name='Descreva o recurso')),
                ('icone', models.CharField(choices=[('lni-rocket', 'foguete'), ('lni-laptop-phone', 'laptop'), ('lni-cog', 'engrenagem'), ('lni-cog', 'folha'), ('lni-leaf', 'papeis')], max_length=20, verbose_name='Icone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
